# app.yaml

application: macro-context-643
version: 1
runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: static/stylesheets

- url: /images
  static_dir: static/images

- url: /(.*\.html)$
  static_files: static/\1
  upload: static/.*\.html$

- url: /profile/.*
  script: _go_app
  login: required

- url: /admin/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
  login: optional